### ISSUE TITLE
Process failing with "Unexpected token ["

### ISSUE THREAD

**Issue by agilefox** [screeps/screeps#10]
Running into the following when I run 'screeps start'

Using:
Server build 35
**Node**: '5.8.0'
**Python** 2.7.9 (default, Feb 10 2015, 03:28:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin

```
[backend] process 50297 started
/usr/local/lib/node_modules/screeps/node_modules/@screeps/backend/lib/utils.js:27
    var [match,hor,x,ver,y] = name.match(/^(\w)(\d+)(\w)(\d+)$/);
        ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/screeps/node_modules/@screeps/backend/lib/game/socket/system.js:3:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
[backend] process 50297 exited with code 1, restarting...
Game time set to 16
```

**Comment by agilefox** [comment]
Just saw this is a duplicate of #4

**Comment by agilefox** [comment]
Re-Opened. At the least, the readme needs to be updated.

**Comment by artch** [comment]
There was a mistake in README.md: the correct required version of Node is 6+, not 4+, since [destructuring assignments](http://node.green/#destructuring--declarations) default support landed only in 6.x. 

README fixed.
