### ISSUE TITLE
Error Installing @screeps/driver@4.3.2

### ISSUE THREAD

**Issue by onlineth** [screeps/screeps#106]
https://asciinema.org/a/gYS1ErDIahkypKwtcog5QQR0Z

Appears to be an issue installing `@screeps/driver@4.3.2`. Output below,

```
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /root/screeps/node_modules/@screeps/driver/node_modules/isolated-vm/build/Release/isolated_vm.node)
    at Object..node (internal/modules/cjs/loader.js:817:18)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/root/screeps/node_modules/@screeps/driver/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function._load (internal/modules/cjs/loader.js:556:12)

/root/screeps/node_modules/webpack-shell-plugin/lib/index.js:168
        throw error;
        ^
1
npm WARN enoent ENOENT: no such file or directory, open '/root/screeps/package.json'
npm WARN screeps No description
npm WARN screeps No repository field.
npm WARN screeps No README data
npm WARN screeps No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @screeps/driver@4.3.2 install: `node-gyp rebuild -C native && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @screeps/driver@4.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-23T04_39_02_541Z-debug.log

```

**Comment by o4kapuk** [comment]
Please check if you have a similar issue with [isolated-vm](https://github.com/laverdet/isolated-vm). Ensure that your system is compatible with IVM.
If you're able to to build IVM but not screeps, please report `uname -a` and `node --version` here.

**Comment by onlineth** [comment]
For `uname -a` and `node --version`, see output below,

```
# uname -a
Linux server11.onlineth.com 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
# node --version
v12.6.0
```

As for isolated-vm, I have a feeling that may be the issue - but the install _seems_ to install fine, output below,

https://asciinema.org/a/NtxErzPS7K3W4A5DQeIkzKfFP

```
+ isolated-vm@2.0.0
updated 1 package and audited 1920 packages in 41.025s
found 32 vulnerabilities (8 low, 4 moderate, 20 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by o4kapuk** [comment]
Nodejs v12 is not supported, please use versions 10.15+ or 8.12.2+

**Comment by onlineth** [comment]
Even chancing to NodeJS v10.16.0, the issue still occurs,

https://asciinema.org/a/lv4rf1z99u1y1bgch1ymApUxf

**Comment by onlineth** [comment]
@o4kapuk Can this ticket be reopened?

**Comment by o4kapuk** [comment]
@onlineth Which linux is this?

**Comment by onlineth** [comment]
CentOS 7 if that's your question

**Comment by o4kapuk** [comment]
@onlineth yes it is
We didn't test builds on CentOS, from the error message your setup doesn't have a library required by isolated-vm. Are you able to build ivm 1.7.10 which we use?

**Comment by o4kapuk** [comment]
@onlineth Seen this? https://stackoverflow.com/questions/48831881/centos-7-libstdc-so-6-version-cxxabi-1-3-9-not-found
