### ISSUE TITLE
Error installing screeps server

### ISSUE THREAD

**Issue by netnutmike** [screeps/screeps#110]
There is another post that is similar to mine but I have checked the versions.  When I run:
` nxp screeps init` I get the following error:

`screeps@screeps:~/world$ npx screeps init
In file included from ../src/pf.cc:2:0:
../src/pf.h: In member function ‘screeps::world_position_t screeps::world_position_t::position_in_direction(screeps::world_position_t::direction_t) const’:
../src/pf.h:128:4: warning: control reaches end of non-void function [-Wreturn-type]
    }
    ^
module.js:550
    throw err;
    ^

Error: Cannot find module './build/Release/isolated_vm'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/screeps/.npm/_npx/13414/lib/node_modules/screeps/node_modules/isolated-vm/isolated-vm.js:1:80)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

/home/screeps/.npm/_npx/13414/lib/node_modules/screeps/node_modules/webpack-shell-plugin/lib/index.js:168
        throw error;
        ^
1
`

I installed Ubuntu 18.04.3 in a VM on my desktop.  I followed the guide on installing on linux.

Here are the version details:

`screeps@screeps:~/world$ uname -a
Linux screeps 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
screeps@screeps:~/world$ node --version
v8.16.2`

I am hoping you can provide some guidance on how to get it to install so I can test some changes prior to making them on the real server.

**Comment by ags131** [comment]
Node 10 is required now, update to node 10 LTS and it should build.

**Comment by netnutmike** [comment]
I upgraded to node 10.17.0 and the same error still occurs.  However, it continues and asks for the API key which is different.

**Comment by netnutmike** [comment]
Here is the error when starting the server (and the node -v is at the bottom.

`screeps@screeps:~/world$ npx screeps start
In file included from ../src/pf.cc:2:0:
../src/pf.h: In member function ‘screeps::world_position_t screeps::world_position_t::position_in_direction(screeps::world_position_t::direction_t) const’:
../src/pf.h:128:4: warning: control reaches end of non-void function [-Wreturn-type]
    }
    ^
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './build/Release/isolated_vm'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/screeps/.npm/_npx/9253/lib/node_modules/screeps/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

/home/screeps/.npm/_npx/9253/lib/node_modules/screeps/node_modules/webpack-shell-plugin/lib/index.js:168
        throw error;
        ^
1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @screeps/driver@5.0.0 install: `node-gyp rebuild -C native && webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @screeps/driver@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/screeps/.npm/_logs/2019-10-23T02_11_33_183Z-debug.log
Install for screeps@latest failed with code 1
screeps@screeps:~/world$ node -v
v10.17.0
`

**Comment by artch** [comment]
You're missing `isolated-vm` module in your `node_modules` folder. Try `npm rebuild` or reinstalling the everything from scratch.

**Comment by netnutmike** [comment]
I created a new VM and reloaded everything from scratch, following the step by step guide.  The only thing I changed is I installed node 10 instead of 8 per the instructions.  I tried the npm rebuild with no success.

After the full os build and install I am still getting the following error.  However, everything seems to be running just fine, even with the error.

```
screeps@screeps:~/world$ npx screeps start
In file included from ../src/pf.cc:2:0:
../src/pf.h: In member function ‘screeps::world_position_t screeps::world_position_t::position_in_direction(screeps::world_position_t::direction_t) const’:
../src/pf.h:128:4: warning: control reaches end of non-void function [-Wreturn-type]
    }
    ^
Server version 4.0.5
```

**Comment by artch** [comment]
What does it show if you try the following?
```
npx node-gyp rebuild -C node_modules/@screeps/driver/native
```

**Comment by C0rn3j** [comment]
```
% pacman -Q npm nodejs python2 node-gyp
npm 7.10.0-1
nodejs 15.14.0-1
python2 2.7.18-3
node-gyp 7.1.2-1
```
---
`npm install` in git cloned repo:
[2021-04-16T18_27_23_996Z-debug.log](https://github.com/screeps/screeps/files/6327229/2021-04-16T18_27_23_996Z-debug.log)
```bash
cd /tmp
git clone https://github.com/screeps/screeps
cd screeps
npm install
```
---
`npm install screeps`:
[2021-04-16T18_29_29_023Z-debug.log](https://github.com/screeps/screeps/files/6327233/2021-04-16T18_29_29_023Z-debug.log)

It doesn't look like the required `@screeps` directory is there at all after running npm install?
```bash
% ls -lah ~/node_modules/@screeps                                                
lsd: /home/c0rn3j/node_modules/@screeps: No such file or directory (os error 2).
```

**Comment by DoctorDerek** [comment]
@Corn3j I think it would just be the `screeps` directory, the @ character indicates scope for [`npm install`](https://docs.npmjs.com/cli/v7/commands/npm-install)

**Comment by ags131** [comment]
First thing, you need to use Node 10, thats what screeps is currently built for. I usually use nvm to make that easy. second, don't clone the repo, just create a folder, `npm init` to start a package, and `npm install --save screeps` to install screeps in that folder. then you can `npx screeps start` from there. Or if you want the easy way, checkout [screeps-launcher](https://github.com/screepers/screeps-launcher), its a single binary download and manages its own copy of node and the npm stuff for you.

**Comment by C0rn3j** [comment]
>First thing, you need to use Node 10, thats what screeps is currently built for. 

```
Prerequisites:
Node.js 10 LTS or higher
```
The README.MD should then be changed, because it currently supports 10 >=, not 10 == 

I swapped nodejs for `nodejs-lts-dubnium 10.24.0-1` and did the following:
```bash
mkdir /tmp/test
cd /tmp/test
node init # ENTER all
npm install --save screeps
```
Still crashes - [2021-04-16T19_02_27_672Z-debug.log](https://github.com/screeps/screeps/files/6327384/2021-04-16T19_02_27_672Z-debug.log)

**Comment by legion0** [comment]
newer version of node don't work, you have to go back to node 12 at the latest, I got this to work with:
```
# install nvm from https://github.com/nvm-sh/nvm#installing-and-updating
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

# install node 12
nvm install v12.22.10

# set node 12 as current
nvm use v12.22.10
```
