### ISSUE TITLE
Steam Web API connection error Error: HTTP 403

### ISSUE THREAD

**Issue by lZzozZl** [screeps/screeps#12]
I'm trying to start Screeps server from my steam client with Start server option. 

Im using Windows7 64 bit. My steam acount is not beta participiant, 

At backend tab i see this message:
Loading mods from "D:\Steam\steamapps\common\Screeps\server\mods.json"
Connecting to storage
Starting CLI server
STEAM_KEY environment variable found, disabling native authentication
Connecting to Steam Web API
CLI listening on localhost:21026
Steam Web API connection error Error: HTTP 403 Forbidden
    at IncomingMessage.<anonymous> (D:\Steam\steamapps\common\Screeps\server\node_modules\steam-webapi\index.js:154:37)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Starting game server (protocol version 12)
SockJS v0.3.18 bound to "/socket"
Game server listening on 0.0.0.0:21025
[127.0.0.1:65368] Incoming CLI connection
Connecting to Steam Web API
Running cronjob 'sendNotifications'
Running cronjob 'roomsForceUpdate'
Running cronjob 'genPowerBanks'
Running cronjob 'genInvaders'
Running cronjob 'purgeTransactions'
Running cronjob 'recreateNpcOrders'
Running cronjob 'calcMarketStats'
Steam Web API connection error Error: HTTP 403 Forbidden
    at IncomingMessage.<anonymous> (D:\Steam\steamapps\common\Screeps\server\node_modules\steam-webapi\index.js:154:37)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Connecting to Steam Web API
Steam Web API connection error Error: HTTP 403 Forbidden
    at IncomingMessage.<anonymous> (D:\Steam\steamapps\common\Screeps\server\node_modules\steam-webapi\index.js:154:37)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Connecting to Steam Web API
Steam Web API connection error Error: HTTP 403 Forbidden
    at IncomingMessage.<anonymous> (D:\Steam\steamapps\common\Screeps\server\node_modules\steam-webapi\index.js:154:37)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Connecting to Steam Web API
Steam Web API connection error Error: HTTP 403 Forbidden
    at IncomingMessage.<anonymous> (D:\Steam\steamapps\common\Screeps\server\node_modules\steam-webapi\index.js:154:37)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Connecting to Steam Web API

**Comment by artch** [comment]
There was a deployment error in the latest version, please update your client and try again.

**Comment by gentili** [comment]
I'm still having this error on my OSX 10.11.6 installation.

**Comment by Ondalf** [comment]
Still happens on fresh Steam install. Same 403 Forbidden. Running Win10 64bit.
