### ISSUE TITLE
Issues with isolated-vm when installing

### ISSUE THREAD

**Issue by Lothornian** [screeps/screeps#122]
When I install the screeps server on a Linux VM in AWS I am consistently running into an issue during the install. When NPM is running the command `node-gyp rebuild --release -j 4` make fails with exit code 2. The full output of `npm install -g screeps` is below. 

If I install isolated-vm directly `npm install isolated-vm' everything works without a problem. 
I have tried Amazon's linux distro and Ubuntu and get the same error on both. In all cases, it is a new VM.

I used Amazon's tutorial to install node: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up-node-on-ec2-instance.html

```
screeps]$ npm install -g screeps
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jquery.terminal@0.11.23: Scroll issue in Chrome fixed in version 1.0.5
/home/ec2-user/.nvm/versions/node/v14.0.0/bin/screeps -> /home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/bin/screeps.js

> isolated-vm@2.1.0 install /home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/isolated-vm
> node-gyp rebuild --release -j 4

make: Entering directory `/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/isolated-vm/build'
  CXX(target) Release/obj.target/nortti/src/external_copy_nortti.o
  AR(target) Release/obj.target/nortti.a
  COPY Release/nortti.a
  CXX(target) Release/obj.target/isolated_vm/src/isolate/allocator.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/class_handle.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/environment.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/executor.o
In file included from ../src/isolate/environment.cc:4:0:
../src/isolate/platform_delegate.h:222:8: error: ‘void ivm::PlatformDelegate::CallOnForegroundThread(v8::Isolate*, v8::Task*)’ marked ‘final’, but is not virtual
   void CallOnForegroundThread(v8::Isolate* isolate, v8::Task* task) final {
        ^~~~~~~~~~~~~~~~~~~~~~
../src/isolate/platform_delegate.h:234:8: error: ‘void ivm::PlatformDelegate::CallDelayedOnForegroundThread(v8::Isolate*, v8::Task*, double)’ marked ‘final’, but is not virtual
   void CallDelayedOnForegroundThread(v8::Isolate* isolate, v8::Task* task, double delay_in_seconds) final {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/isolate/platform_delegate.h:262:8: error: ‘void ivm::PlatformDelegate::CallIdleOnForegroundThread(v8::Isolate*, v8::IdleTask*)’ marked ‘final’, but is not virtual
   void CallIdleOnForegroundThread(v8::Isolate* isolate, v8::IdleTask* task) final {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/isolate/platform_delegate.h: In member function ‘void ivm::PlatformDelegate::CallOnForegroundThread(v8::Isolate*, v8::Task*)’:
../src/isolate/platform_delegate.h:230:20: error: ‘class v8::Platform’ has no member named ‘CallOnForegroundThread’; did you mean ‘CallOnWorkerThread’?
     node_platform->CallOnForegroundThread(isolate, task);
                    ^~~~~~~~~~~~~~~~~~~~~~
                    CallOnWorkerThread
../src/isolate/platform_delegate.h: In member function ‘void ivm::PlatformDelegate::CallDelayedOnForegroundThread(v8::Isolate*, v8::Task*, double)’:
../src/isolate/platform_delegate.h:248:20: error: ‘class v8::Platform’ has no member named ‘CallDelayedOnForegroundThread’; did you mean ‘CallDelayedOnWorkerThread’?
     node_platform->CallDelayedOnForegroundThread(isolate, task, delay_in_seconds);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    CallDelayedOnWorkerThread
../src/isolate/platform_delegate.h: In member function ‘void ivm::PlatformDelegate::CallIdleOnForegroundThread(v8::Isolate*, v8::IdleTask*)’:
../src/isolate/platform_delegate.h:263:19: error: ‘class v8::Platform’ has no member named ‘CallIdleOnForegroundThread’; did you mean ‘CallOnWorkerThread’?
    node_platform->CallIdleOnForegroundThread(isolate, task);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
                   CallOnWorkerThread
  CXX(target) Release/obj.target/isolated_vm/src/isolate/holder.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/inspector.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/scheduler.o
make: *** [Release/obj.target/isolated_vm/src/isolate/environment.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/isolated-vm/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.14.173-137.229.amzn2.x86_64
gyp ERR! command "/home/ec2-user/.nvm/versions/node/v14.0.0/bin/node" "/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
gyp ERR! cwd /home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/isolated-vm
gyp ERR! node -v v14.0.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/screeps/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules/screeps/node_modules/fsevents/node_modules/abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/abbrev' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.abbrev.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules/screeps/node_modules/fsevents/node_modules/ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/ansi-regex' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: aproba@1.2.0 (node_modules/screeps/node_modules/fsevents/node_modules/aproba):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/aproba' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.aproba.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: balanced-match@1.0.0 (node_modules/screeps/node_modules/fsevents/node_modules/balanced-match):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/balanced-match' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.balanced-match.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chownr@1.1.4 (node_modules/screeps/node_modules/fsevents/node_modules/chownr):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/chownr' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.chownr.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: code-point-at@1.1.0 (node_modules/screeps/node_modules/fsevents/node_modules/code-point-at):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/code-point-at' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.code-point-at.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: concat-map@0.0.1 (node_modules/screeps/node_modules/fsevents/node_modules/concat-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/concat-map' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.concat-map.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: console-control-strings@1.1.0 (node_modules/screeps/node_modules/fsevents/node_modules/console-control-strings):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/console-control-strings' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.console-control-strings.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-util-is@1.0.2 (node_modules/screeps/node_modules/fsevents/node_modules/core-util-is):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/core-util-is' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.core-util-is.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: deep-extend@0.6.0 (node_modules/screeps/node_modules/fsevents/node_modules/deep-extend):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/deep-extend' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.deep-extend.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: delegates@1.0.0 (node_modules/screeps/node_modules/fsevents/node_modules/delegates):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/delegates' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.delegates.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: detect-libc@1.0.3 (node_modules/screeps/node_modules/fsevents/node_modules/detect-libc):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/detect-libc' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.detect-libc.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs.realpath@1.0.0 (node_modules/screeps/node_modules/fsevents/node_modules/fs.realpath):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/fs.realpath' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.fs.realpath.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.1 (node_modules/screeps/node_modules/fsevents/node_modules/has-unicode):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/has-unicode' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.has-unicode.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inherits@2.0.4 (node_modules/screeps/node_modules/fsevents/node_modules/inherits):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/inherits' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.inherits.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ini@1.3.5 (node_modules/screeps/node_modules/fsevents/node_modules/ini):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/ini' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.ini.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isarray@1.0.0 (node_modules/screeps/node_modules/fsevents/node_modules/isarray):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/isarray' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.isarray.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.5 (node_modules/screeps/node_modules/fsevents/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/minimist' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ms@2.1.2 (node_modules/screeps/node_modules/fsevents/node_modules/ms):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/ms' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.ms.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npm-normalize-package-bin@1.0.1 (node_modules/screeps/node_modules/fsevents/node_modules/npm-normalize-package-bin):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/npm-normalize-package-bin' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.npm-normalize-package-bin.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: number-is-nan@1.0.1 (node_modules/screeps/node_modules/fsevents/node_modules/number-is-nan):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/number-is-nan' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.number-is-nan.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: object-assign@4.1.1 (node_modules/screeps/node_modules/fsevents/node_modules/object-assign):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/object-assign' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.object-assign.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-homedir@1.0.2 (node_modules/screeps/node_modules/fsevents/node_modules/os-homedir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/os-homedir' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.os-homedir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-tmpdir@1.0.2 (node_modules/screeps/node_modules/fsevents/node_modules/os-tmpdir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/os-tmpdir' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.os-tmpdir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: path-is-absolute@1.0.1 (node_modules/screeps/node_modules/fsevents/node_modules/path-is-absolute):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/path-is-absolute' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.path-is-absolute.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: process-nextick-args@2.0.1 (node_modules/screeps/node_modules/fsevents/node_modules/process-nextick-args):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/process-nextick-args' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.process-nextick-args.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safe-buffer@5.1.2 (node_modules/screeps/node_modules/fsevents/node_modules/safe-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/safe-buffer' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.safe-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safer-buffer@2.1.2 (node_modules/screeps/node_modules/fsevents/node_modules/safer-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/safer-buffer' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.safer-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sax@1.2.4 (node_modules/screeps/node_modules/fsevents/node_modules/sax):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/sax' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.sax.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: semver@5.7.1 (node_modules/screeps/node_modules/fsevents/node_modules/semver):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/semver' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.semver.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: set-blocking@2.0.0 (node_modules/screeps/node_modules/fsevents/node_modules/set-blocking):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/set-blocking' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.set-blocking.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: signal-exit@3.0.2 (node_modules/screeps/node_modules/fsevents/node_modules/signal-exit):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/signal-exit' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.signal-exit.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strip-json-comments@2.0.1 (node_modules/screeps/node_modules/fsevents/node_modules/strip-json-comments):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/strip-json-comments' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.strip-json-comments.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: util-deprecate@1.0.2 (node_modules/screeps/node_modules/fsevents/node_modules/util-deprecate):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/util-deprecate' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.util-deprecate.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wrappy@1.0.2 (node_modules/screeps/node_modules/fsevents/node_modules/wrappy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/wrappy' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.wrappy.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yallist@3.1.1 (node_modules/screeps/node_modules/fsevents/node_modules/yallist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/yallist' -> '/home/ec2-user/.nvm/versions/node/v14.0.0/lib/node_modules/screeps/node_modules/fsevents/node_modules/.yallist.DELETE'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isolated-vm@2.1.0 install: `node-gyp rebuild --release -j 4`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isolated-vm@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2020-04-22T21_13_40_013Z-debug.log
```

**Comment by ags131** [comment]
Use node 10, other versions are not supported.

**Comment by Lothornian** [comment]
After installing node 10.20.0 everything is working. Note current LTS versions 12.16.2 and 14 both see this error. I used nvm to install node 10 with the following commands:
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
nvm install 10
```

Thanks for the help.

**Comment by Jeroendevr** [comment]
> 
> ```
>
> nvm install 10
> ```

Should be **npm** install 10 ?

**Comment by Gadjung** [comment]
he used nvm to install node not npm `10` package

**Comment by Jeroendevr** [comment]
Ah Thanks, I just discovered NodeVersionManager, handy tool it is.

**Comment by vladimmi** [comment]
> Use node 10, other versions are not supported.

Really?..

> Prerequisites:
> - Node.js 10 LTS **or higher**

Current Node LTS is 14, Node 10 is not maintained anymore, yet isolated-vm issues still happen with screeps install.
