### ISSUE TITLE
"npm install screeps" fails 

### ISSUE THREAD

**Issue by wesleyhall** [screeps/screeps#140]
Tried this using both node 10 and 12, the `npm install screeps` command appears to fail with... 

`14349 verbose stack Error: isolated-vm@2.1.1 install: `node-gyp rebuild --release -j 4`
14349 verbose stack Exit status 1
14349 verbose stack     at EventEmitter.<anonymous> (/home/screeps/.nvm/versions/node/v12.22.6/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14349 verbose stack     at EventEmitter.emit (events.js:314:20)
14349 verbose stack     at ChildProcess.<anonymous> (/home/screeps/.nvm/versions/node/v12.22.6/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14349 verbose stack     at ChildProcess.emit (events.js:314:20)
14349 verbose stack     at maybeClose (internal/child_process.js:1022:16)
14349 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14350 verbose pkgid isolated-vm@2.1.1
14351 verbose cwd /home/screeps/world
14352 verbose Linux 5.4.0-73-generic
14353 verbose argv "/home/screeps/.nvm/versions/node/v12.22.6/bin/node" "/home/screeps/.nvm/versions/node/v12.22.6/bin/npm" "install" "screeps"
14354 verbose node v12.22.6
14355 verbose npm  v6.14.15
14356 error code ELIFECYCLE
14357 error errno 1
14358 error isolated-vm@2.1.1 install: `node-gyp rebuild --release -j 4`
14358 error Exit status 1
14359 error Failed at the isolated-vm@2.1.1 install script.
14359 error This is probably not a problem with npm. There is likely additional logging output above.
14360 verbose exit [ 1, true ]
`

**Comment by Kixiron** [comment]
I'm having the same issue, any fixes?
