### ISSUE TITLE
error while installing 

### ISSUE THREAD

**Issue by SNIAPA** [screeps/screeps#149]
node -v 
v16.13.1

npm i screeps
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated jquery.terminal@0.11.23: Scroll issue in Chrome fixed in version 1.0.5
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\huber\\Desktop\\screeps\\node_modules',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\huber\Desktop\screeps\node_modules\isolated-vm'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\huber\\Desktop\\screeps\\node_modules\\isolated-vm'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\huber\Desktop\screeps\node_modules\@screeps\driver
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild -C native && webpack
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
npm ERR!   main.cc
npm ERR!   pf.cc
npm ERR!   win_delay_load_hook.cc
npm ERR! c:\users\huber\desktop\screeps\node_modules\@screeps\driver\native\src\pf.h(128): warning C4715: 'screeps::world_position_t::position_in_direction': not all control paths return a value [C:\Users\huber\Desktop\screeps\node_modules\@screeps\driver\native\build\native.vcxproj]
npm ERR!      Creating library C:\Users\huber\Desktop\screeps\node_modules\@screeps\driver\native\build\Release\native.lib and object C:\Users\huber\Desktop\screeps\node_modules\@screeps\driver\native\build\Release\native.exp
npm ERR!   native.vcxproj -> C:\Users\huber\Desktop\screeps\node_modules\@screeps\driver\native\build\Release\\native.node
npm ERR! Executing post-build scripts
npm ERR! Hash: 7b4e8438825aa87525b9
npm ERR! Version: webpack 3.12.0
npm ERR! Time: 1615ms
npm ERR!             Asset    Size  Chunks                    Chunk Names
npm ERR! runtime.bundle.js  940 kB       0  [emitted]  [big]  main
npm ERR!    [0] ../engine/src/utils.js 21.6 kB {0} [built]
npm ERR!    [2] ../engine/src/game/rooms.js 58.7 kB {0} [built]
npm ERR!    [6] (webpack)/buildin/global.js 509 bytes {0} [built]
npm ERR!    [9] ./lib/runtime/runtime-driver.js 4.15 kB {0} [built]
npm ERR!   [13] ./lib/runtime/runtime.js 11 kB {0} [built]
npm ERR!   [15] (webpack)/buildin/module.js 517 bytes {0} [built]
npm ERR!   [16] ../pathfinding/index.js 48 bytes {0} [built]
npm ERR!   [24] ../engine/src 160 bytes {0} [built]
npm ERR!   [25] ../engine/src/game/game.js 27 kB {0} [built]
npm ERR!   [26] ../engine/src/game/map.js 13.2 kB {0} [built]
npm ERR!   [28] ../engine/src/game/market.js 9.96 kB {0} [built]
npm ERR!   [32] ../engine/src/game/custom-prototypes.js 1.93 kB {0} [built]
npm ERR!   [48] ../engine/src/game/creeps.js 38.1 kB {0} [built]
npm ERR!   [63] ../engine/src/game/console.js 3.21 kB {0} [built]
npm ERR!   [64] ./lib/runtime/mapgrid.js 7.37 kB {0} [built]
npm ERR!     + 50 hidden modules
npm ERR!
npm ERR! WARNING in ../engine/src/utils.js
npm ERR! 17:8-42 Critical dependency: the request of a dependency is an expression
npm ERR!  @ ../engine/src/utils.js
npm ERR!  @ ./lib/runtime/runtime.js
npm ERR! node:internal/modules/cjs/loader:936
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module './build/Release/isolated_vm'
npm ERR! Require stack:
npm ERR! - C:\Users\huber\Desktop\screeps\node_modules\isolated-vm\isolated-vm.js
npm ERR! - C:\Users\huber\Desktop\screeps\node_modules\@screeps\driver\make-runtime-snapshot.js
npm ERR!     at Function._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function._load (node:internal/modules/cjs/loader:778:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at Object.<anonymous> (C:\Users\huber\Desktop\screeps\node_modules\isolated-vm\isolated-vm.js:1:18)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object..js (node:internal/modules/cjs/loader:1153:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     'C:\\Users\\huber\\Desktop\\screeps\\node_modules\\isolated-vm\\isolated-vm.js',
npm ERR!     'C:\\Users\\huber\\Desktop\\screeps\\node_modules\\@screeps\\driver\\make-runtime-snapshot.js'
npm ERR!   ]
npm ERR! }
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp info chdir native
npm ERR! (node:6016) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn C:\Users\huber\.windows-build-tools\python27\python.EXE
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\huber\\Desktop\\screeps\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-G',
npm ERR! gyp info spawn args   'msvs_version=2015',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\huber\\Desktop\\screeps\\node_modules\\@screeps\\driver\\native\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\huber\\Desktop\\screeps\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\huber\\.node-gyp\\16.13.1\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\huber\\.node-gyp\\16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\huber\\Desktop\\screeps\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\Users\\huber\\.node-gyp\\16.13.1\\<(target_arch)\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\huber\\Desktop\\screeps\\node_modules\\@screeps\\driver\\native',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\huber\\Desktop\\screeps\\node_modules\\@screeps\\driver\\native\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! C:\Users\huber\Desktop\screeps\node_modules\webpack-shell-plugin\lib\index.js:168
npm ERR!         throw error;
npm ERR!         ^
npm ERR!
npm ERR! Error: Command failed: node --nolazy make-runtime-snapshot
npm ERR! node:internal/modules/cjs/loader:936
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module './build/Release/isolated_vm'
npm ERR! Require stack:
npm ERR! - C:\Users\huber\Desktop\screeps\node_modules\isolated-vm\isolated-vm.js
npm ERR! - C:\Users\huber\Desktop\screeps\node_modules\@screeps\driver\make-runtime-snapshot.js
npm ERR!     at Function._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function._load (node:internal/modules/cjs/loader:778:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at Object.<anonymous> (C:\Users\huber\Desktop\screeps\node_modules\isolated-vm\isolated-vm.js:1:18)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object..js (node:internal/modules/cjs/loader:1153:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     'C:\\Users\\huber\\Desktop\\screeps\\node_modules\\isolated-vm\\isolated-vm.js',
npm ERR!     'C:\\Users\\huber\\Desktop\\screeps\\node_modules\\@screeps\\driver\\make-runtime-snapshot.js'
npm ERR!   ]
npm ERR! }
npm ERR!
npm ERR!     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR!     at ChildProcess.emit (node:events:390:28)
npm ERR!     at maybeClose (node:internal/child_process:1064:16)
npm ERR!     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
npm ERR!   killed: false,
npm ERR!   code: 1,
npm ERR!   signal: null,
npm ERR!   cmd: 'node --nolazy make-runtime-snapshot'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\huber\AppData\Local\npm-cache\_logs\2021-12-21T19_20_29_317Z-debug.log

[2021-12-21T19_20_29_317Z-debug.log](https://github.com/screeps/screeps/files/7757555/2021-12-21T19_20_29_317Z-debug.log)

**tried downgrading to all kings of node versions (10.13.0, 10.18.0, 10.24.0)
but then i get this error**

npm i screeps
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jquery.terminal@0.11.23: Scroll issue in Chrome fixed in version 1.0.5

> isolated-vm@2.1.1 install C:\Users\huber\Desktop\screeps\node_modules\@screeps\driver\node_modules\isolated-vm
> node-gyp rebuild --release -j 4

C:\Users\huber\Desktop\screeps\node_modules\@screeps\driver\node_modules\isolated-vm>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release -j 4 )  else (node "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" rebuild --release -j 4 )
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\usr\local\lib\node_modules\node-gyp\bin\node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\huber\Desktop\screeps\package.json'
npm WARN screeps No description
npm WARN screeps No repository field.
npm WARN screeps No README data
npm WARN screeps No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isolated-vm@2.1.1 install: `node-gyp rebuild --release -j 4`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isolated-vm@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\huber\AppData\Roaming\npm-cache\_logs\2021-12-21T19_28_04_128Z-debug.log

[2021-12-21T19_28_04_128Z-debug.log](https://github.com/screeps/screeps/files/7757696/2021-12-21T19_28_04_128Z-debug.log)

**Comment by SNIAPA** [comment]
ok so the problem was with node-gyp.
when u downgrade node it somehow creates ghost instalation of node gyp so i nuked nodegyp and reinstaled the downgraded node.
