### ISSUE TITLE
npm install screeps failure on Debian 11.3

### ISSUE THREAD

**Issue by Luna444** [screeps/screeps#155]
I cannot install screeps on Debian 11.3 with freshly installed dependancies.
Here's what the console is displaying:
```
-- displaying all software versions
debian@vps-6cf6f400:~/friendScreeps$ cat /etc/debian_version
11.3
debian@vps-6cf6f400:~/friendScreeps$ nodejs --version
v12.22.5
debian@vps-6cf6f400:~/friendScreeps$ python2 --version
Python 2.7.18
debian@vps-6cf6f400:~/friendScreeps$ sudo apt install build-essential
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
```
-- attempting npm install screeps
debian@vps-6cf6f400:~/friendScreeps$ npm install screeps
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated jquery.terminal@0.11.23: Scroll issue in Chrome fixed in version 1.0.5
npm WARN deprecated angular@1.8.3: For the actively supported Angular, see https://www.npmjs.com/package/@angular/core. AngularJS support has officially ended. For extended AngularJS support options, see https://goo.gle/angularjs-path-forward.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /home/debian/node_modules/@screeps/driver
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild -C native && webpack
npm ERR! make: Entering directory '/home/debian/node_modules/@screeps/driver/native/build'
npm ERR!   CXX(target) Release/obj.target/native/src/main.o
npm ERR!   CXX(target) Release/obj.target/native/src/pf.o
npm ERR!   SOLINK_MODULE(target) Release/obj.target/native.node
npm ERR!   COPY Release/native.node
npm ERR! make: Leaving directory '/home/debian/node_modules/@screeps/driver/native/build'
npm ERR! Executing post-build scripts
npm ERR! Hash: 7b4e8438825aa87525b9
npm ERR! Version: webpack 3.12.0
npm ERR! Time: 2142ms
npm ERR!             Asset    Size  Chunks                    Chunk Names
npm ERR! runtime.bundle.js  940 kB       0  [emitted]  [big]  main
npm ERR!    [0] ../engine/src/utils.js 21.6 kB {0} [built]
npm ERR!    [2] ../engine/src/game/rooms.js 58.7 kB {0} [built]
npm ERR!    [6] (webpack)/buildin/global.js 509 bytes {0} [built]
npm ERR!    [9] ./lib/runtime/runtime-driver.js 4.15 kB {0} [built]
npm ERR!   [13] ./lib/runtime/runtime.js 11 kB {0} [built]
npm ERR!   [15] (webpack)/buildin/module.js 517 bytes {0} [built]
npm ERR!   [16] ../pathfinding/index.js 48 bytes {0} [built]
npm ERR!   [24] ../engine/src 160 bytes {0} [built]
npm ERR!   [25] ../engine/src/game/game.js 27 kB {0} [built]
npm ERR!   [26] ../engine/src/game/map.js 13.2 kB {0} [built]
npm ERR!   [28] ../engine/src/game/market.js 9.96 kB {0} [built]
npm ERR!   [32] ../engine/src/game/custom-prototypes.js 1.93 kB {0} [built]
npm ERR!   [48] ../engine/src/game/creeps.js 38.1 kB {0} [built]
npm ERR!   [63] ../engine/src/game/console.js 3.21 kB {0} [built]
npm ERR!   [64] ./lib/runtime/mapgrid.js 7.37 kB {0} [built]
npm ERR!     + 50 hidden modules
npm ERR!
npm ERR! WARNING in ../engine/src/utils.js
npm ERR! 17:8-42 Critical dependency: the request of a dependency is an expression
npm ERR!  @ ../engine/src/utils.js
npm ERR!  @ ./lib/runtime/runtime.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@12.22.5 | linux | x64
npm ERR! gyp info chdir native
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/debian/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/debian/node_modules/@screeps/driver/native/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/debian/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/debian/.node-gyp/12.22.5/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/debian/.node-gyp/12.22.5',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/debian/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/debian/.node-gyp/12.22.5/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/debian/node_modules/@screeps/driver/native',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../../../../nan/nan.h:58,
npm ERR!                  from ../src/main.cc:2:
npm ERR! /home/debian/.node-gyp/12.22.5/include/node/node.h:736:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
npm ERR!   736 |       (node::addon_register_func) (regfunc),                          \
npm ERR!       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! /home/debian/.node-gyp/12.22.5/include/node/node.h:770:3: note: in expansion of macro ‘NODE_MODULE_X’
npm ERR!   770 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
npm ERR!       |   ^~~~~~~~~~~~~
npm ERR! ../src/main.cc:63:1: note: in expansion of macro ‘NODE_MODULE’
npm ERR!    63 | NODE_MODULE(native, init);
npm ERR!       | ^~~~~~~~~~~
npm ERR! ../src/pf.cc: In member function ‘v8::Local<v8::Value> screeps::path_finder_t::search(v8::Local<v8::Value>, v8::Local<v8::Array>, v8::Local<v8::Function>, screeps::cost_t, screeps::cost_t, uint8_t, uint32_t, uint32_t, bool, double)’:
npm ERR! ../src/pf.cc:563:12: warning: catching polymorphic type ‘class screeps::path_finder_t::js_error’ by value [-Wcatch-value=]
npm ERR!   563 |   } catch (js_error) {
npm ERR!       |            ^~~~~~~~
npm ERR! In file included from ../src/pf.cc:2:
npm ERR! ../src/pf.h: In member function ‘screeps::world_position_t screeps::world_position_t::position_in_direction(screeps::world_position_t::direction_t) const’:
npm ERR! ../src/pf.h:128:4: warning: control reaches end of non-void function [-Wreturn-type]
npm ERR!   128 |    }
npm ERR!       |    ^
npm ERR! gyp info ok
npm ERR! internal/modules/cjs/loader.js:818
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module './build/Release/isolated_vm'
npm ERR! Require stack:
npm ERR! - /home/debian/node_modules/isolated-vm/isolated-vm.js
npm ERR! - /home/debian/node_modules/@screeps/driver/make-runtime-snapshot.js
npm ERR!     at Function._resolveFilename (internal/modules/cjs/loader.js:815:15)
npm ERR!     at Function._load (internal/modules/cjs/loader.js:667:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:74:18)
npm ERR!     at Object.<anonymous> (/home/debian/node_modules/isolated-vm/isolated-vm.js:1:18)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR!     at Object..js (internal/modules/cjs/loader.js:1027:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR!     at Function._load (internal/modules/cjs/loader.js:708:14)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:887:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/home/debian/node_modules/isolated-vm/isolated-vm.js',
npm ERR!     '/home/debian/node_modules/@screeps/driver/make-runtime-snapshot.js'
npm ERR!   ]
npm ERR! }
npm ERR!
npm ERR! /home/debian/node_modules/webpack-shell-plugin/lib/index.js:168
npm ERR!         throw error;
npm ERR!         ^
npm ERR! 1
npm ERR! (Use `node --trace-uncaught ...` to show where the exception was thrown)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/debian/.npm/_logs/2022-04-18T20_20_23_644Z-debug.log
```

**Comment by IzzleNizzle** [comment]
Docs recommend using ubuntu 16. Looks like your using the right version of python and node.

If you can't switch OS,  maybe use a docker container

**Comment by Qionglu735** [comment]
Try downgrade nodejs to 10.x
```
  curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  apt install -y nodejs
```
Doesn't know which the highest version is. my lastest successful try is v10.24.1

**Comment by Qionglu735** [comment]
> I fixed the problem by installing nodejs with nvm instead of the system package manager. NodeJS install was bad.

Good to know. Which version of nodejs you use to fix it ?

**Comment by Luna444** [comment]
I installed the latest version, and it worked.
