### ISSUE TITLE
Dockerized Screeps Server

### ISSUE THREAD

**Issue by ArronHoltzhausen** [screeps/screeps#21]
So i managed to get a docker container of this git repo up and running. with a working server. 

iv played around with it and have a question about  the Modules, 
Each module has its own git repo. and Im trying to figure out how to configure a repo to use it. 

i know it may be a nooby question. but Im unclear with the current documentation on how to do it. 

If anyone wants to know how i got the dockerized stuff working. ill be creating a repo soon enough with the DockerFile and setup scripts. 

Thanks for working on this Project! I think its awesome.

**Comment by ags131** [comment]
Theres also ags131/screeps-server on Docker hub also :)

**Comment by artch** [comment]
@ArronHoltzhausen So what exactly do you want to achieve, and what's the exact question?

**Comment by ArronHoltzhausen** [comment]
Hi @artch, iv sort of come right on my own. but Im basically curious as to how to add the extra modules such as recording room history etc/statistics/player sandbox

my mods.json looks like the following

 "mods": [
    "mods/welcome-text.js",
    "mods/tick-duration.js",
    "mods/change-constant.js",
    "mods/cli-method.js",
    "mods/cronjob.js",
    "mods/driver-method.js",
    "mods/http-endpoint.js",
    "mods/notifications-mailer/notifications-mailer.js",
    "mods/player-sandbox.js",
    "mods/process-object.js",
    "mods/room-history.js",
    "mods/custom-objects/simple.js",
    "mods/custom-objects/advanced.js",
    "mods/custom-objects/intent.js",
    "mods/custom-objects/intent-custom.js"
  ]

which is basically a minor alteration from your example-mods section. (path)
but whenever the server spins up i get problems


```
Error loading "/opt/mods/player-sandbox.js": TypeError: config.engine.on is not a function
at module.exports (/opt/mods/player-sandbox.js:5:23)
at modsJson.mods.forEach.file (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:36:21)
at Array.forEach (native)
at Object.exports.load (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:28:23)
at Object.exports.connect (/usr/local/lib/node_modules/screeps/node_modules/@screeps/driver/lib/index.js:80:26)
at Object. (/usr/local/lib/node_modules/screeps/node_modules/@screeps/engine/dist/main.js:114:8)
at Module._compile (module.js:573:32)
at Object.Module._extensions..js (module.js:582:10)
at Module.load (module.js:490:32)
at tryModuleLoad (module.js:449:12)
Error loading "/opt/mods/process-object.js": TypeError: config.engine.on is not a function
at module.exports (/opt/mods/process-object.js:5:23)
at modsJson.mods.forEach.file (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:36:21)
at Array.forEach (native)
at Object.exports.load (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:28:23)
at Object.exports.connect (/usr/local/lib/node_modules/screeps/node_modules/@screeps/driver/lib/index.js:80:26)
at Object. (/usr/local/lib/node_modules/screeps/node_modules/@screeps/engine/dist/main.js:114:8)
at Module._compile (module.js:573:32)
at Object.Module._extensions..js (module.js:582:10)
at Module.load (module.js:490:32)
at tryModuleLoad (module.js:449:12)
Error loading "/opt/mods/room-history.js": TypeError: config.engine.on is not a function
at module.exports (/opt/mods/room-history.js:13:23)
at modsJson.mods.forEach.file (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:36:21)
at Array.forEach (native)
at Object.exports.load (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:28:23)
at Object.exports.connect (/usr/local/lib/node_modules/screeps/node_modules/@screeps/driver/lib/index.js:80:26)
at Object. (/usr/local/lib/node_modules/screeps/node_modules/@screeps/engine/dist/main.js:114:8)
at Module._compile (module.js:573:32)
at Object.Module._extensions..js (module.js:582:10)
at Module.load (module.js:490:32)
at tryModuleLoad (module.js:449:12)
/opt/mods/custom-objects/simple.js
Error loading "/opt/mods/custom-objects/advanced.js": TypeError: config.engine.on is not a function
at module.exports (/opt/mods/custom-objects/advanced.js:34:23)
at modsJson.mods.forEach.file (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:36:21)
at Array.forEach (native)
at Object.exports.load (/usr/local/lib/node_modules/screeps/node_modules/@screeps/common/lib/config-manager.js:28:23)
at Object.exports.connect (/usr/local/lib/node_modules/screeps/node_modules/@screeps/driver/lib/index.js:80:26)
at Object. (/usr/local/lib/node_modules/screeps/node_modules/@screeps/engine/dist/main.js:114:8)
at Module._compile (module.js:573:32)
at Object.Module._extensions..js (module.js:582:10)
at Module.load (module.js:490:32)
at tryModuleLoad (module.js:449:12)
```
im not sure if npm is bugging me around.

**Comment by artch** [comment]
What is your server version?

**Comment by ArronHoltzhausen** [comment]
everything is the latest. when i rebuild a container it does npm install -g screeps

**Comment by artch** [comment]
> screeps@1.0.7

The latest is 2.1.3. Please try to do a clean re-install.

**Comment by ArronHoltzhausen** [comment]
@artch  this solved my issue! thank you!. but for some reason i still cant get player_sandbox to work? even tho the mod loaded successfully.

**Comment by artch** [comment]
What do you get and what do you expect?

**Comment by ArronHoltzhausen** [comment]
When I log into the server I assumed that the "Simulation" option would appear, or is that not the intent ?

**Comment by artch** [comment]
Simulation doesn't make any sense on private servers. `player-sandbox` mod is for adding custom functionality to player script space, such as new API methods or properties.
