### ISSUE TITLE
Steam Web API connection error Error: HTTP 403 Forbidden

### ISSUE THREAD

**Issue by gentili** [screeps/screeps#23]
I'm still getting this error in backend.log with latest version of screeps on OSX 10.11.6:

Loading mods from "/Users/gentili/Library/Application Support/Steam/SteamApps/common/Screeps/server/mods.json"
Connecting to storage
Starting CLI server
STEAM_KEY environment variable found, disabling native authentication
Connecting to Steam Web API
CLI listening on localhost:21026
[127.0.0.1:49486] Incoming CLI connection
Steam Web API connection error Error: HTTP 403 Forbidden
    at IncomingMessage.<anonymous> (/Users/gentili/Library/Application Support/Steam/SteamApps/common/Screeps/server/node_modules/steam-webapi/index.js:154:37)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Starting game server (protocol version 12)
SockJS v0.3.18 bound to "/socket"
Game server listening on 0.0.0.0:21025
Connecting to Steam Web API
Running cronjob 'sendNotifications'
Running cronjob 'roomsForceUpdate'
Running cronjob 'genPowerBanks'
Running cronjob 'genInvaders'
Running cronjob 'purgeTransactions'
Running cronjob 'recreateNpcOrders'
Running cronjob 'calcMarketStats'
Steam Web API connection error Error: HTTP 403 Forbidden
    at IncomingMessage.<anonymous> (/Users/gentili/Library/Application Support/Steam/SteamApps/common/Screeps/server/node_modules/steam-webapi/index.js:154:37)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Connecting to Steam Web API
Steam Web API connection error Error: HTTP 403 Forbidden
    at IncomingMessage.<anonymous> (/Users/gentili/Library/Application Support/Steam/SteamApps/common/Screeps/server/node_modules/steam-webapi/index.js:154:37)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Connecting to Steam Web API
Steam Web API connection error Error: HTTP 403 Forbidden
    at IncomingMessage.<anonymous> (/Users/gentili/Library/Application Support/Steam/SteamApps/common/Screeps/server/node_modules/steam-webapi/index.js:154:37)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by artch** [comment]
Could you please attack your `/Users/gentili/Library/Application Support/Steam/SteamApps/common/Screeps/server/.screepsrc` file?

**Comment by Kedirech** [comment]
I was getting this error, I had the wrong API key entered.  Correcting in the .screepsrc file seemed to fix it.

**Comment by NickiHell** [comment]
Same error, Mint 18.1, 4-4-0-59 generic.

**Comment by SystemParadox** [comment]
To anyone else having issues with this in the future, note that this requires a ***STEAM*** API key (http://steamcommunity.com/dev/apikey), NOT a screeps auth token!
