### ISSUE TITLE
Syntax error running screeps

### ISSUE THREAD

**Issue by blindly** [screeps/screeps#4]
I'm getting the following message starting screeps:

```
SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/screeps/server/node_modules/@screeps/backend/lib/game/socket/system.js:3:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
[backend] process 30794 exited with code 1, restarting...
Game time set to 42
[backend] process 30799 started
Game time set to 43
/home/screeps/server/node_modules/@screeps/backend/lib/utils.js:27
    var [match,hor,x,ver,y] = name.match(/^(\w)(\d+)(\w)(\d+)$/);
```

$ node -v
v4.2.4

**Comment by blindly** [comment]
I have managed to work around this by using nodeenv.

$ node -v
v7.1.0

No errors
