### ISSUE TITLE
Windows headless server - Module version mismatch

### ISSUE THREAD

**Issue by elgskred** [screeps/screeps#46]
When starting the server with "screeps -start" the logs return:
Using Node verion 6.9.5 and python version 2.7

```
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Server\AppData\Roaming\npm\node_modules\screeps\node_modules\@screeps\driver\lib\index.js:941:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

I've installed using the guide found here https://github.com/screeps/screeps

**Comment by artch** [comment]
This error may indicate that you installed the package using the different Node.js version that you try to run. Try to do full clean reinstall, removing all contents of `C:\Users\Server\AppData\Roaming\npm\node_modules\screeps`.

**Comment by elgskred** [comment]
That fixed it. 
Thanks
