### ISSUE TITLE
Error installing on Azure CentOS VM

### ISSUE THREAD

**Issue by gehnster** [screeps/screeps#48]
Here is the error I get. Note I've tried this as root and sudo. If I don't use sudo as my normal user it just gives me an EACCS error. I've also tried installing on a Azure windows vm and it gives me the same error.

```
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/bin/screeps -> /usr/lib/node_modules/screeps/bin/screeps.js

> weak@1.0.1 install /usr/lib/node_modules/screeps/node_modules/weak
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.9.5"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/screeps/node_modules/weak/.node-gyp"
make: Entering directory `/usr/lib/node_modules/screeps/node_modules/weak/build'
  CXX(target) Release/obj.target/weakref/src/weakref.o
make: g++: Command not found
make: *** [Release/obj.target/weakref/src/weakref.o] Error 127
make: Leaving directory `/usr/lib/node_modules/screeps/node_modules/weak/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.0-514.2.2.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/screeps/node_modules/weak
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> @screeps/driver@2.1.0 install /usr/lib/node_modules/screeps/node_modules/@screeps/driver
> node-gyp rebuild -C native

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.9.5"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/screeps/node_modules/@screeps/driver/.node-gyp"
make: Entering directory `/usr/lib/node_modules/screeps/node_modules/@screeps/driver/native/build'
  CXX(target) Release/obj.target/native/src/main.o
make: g++: Command not found
make: *** [Release/obj.target/native/src/main.o] Error 127
make: Leaving directory `/usr/lib/node_modules/screeps/node_modules/@screeps/driver/native/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.0-514.2.2.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-C" "native"
gyp ERR! cwd /usr/lib/node_modules/screeps/node_modules/@screeps/driver/native
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
/usr/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules/screeps/node_modules/weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Linux 3.10.0-514.2.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "-g" "screeps"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! @screeps/driver@2.1.0 install: `node-gyp rebuild -C native`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @screeps/driver@2.1.0 install script 'node-gyp rebuild -C native'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @screeps/driver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild -C native
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @screeps/driver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @screeps/driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gehn/npm-debug.log
npm ERR! code 1
```

**Comment by gehnster** [comment]
Just tried with Ubuntu 16.04 on VirtualBox. Same error.

**Comment by ags131** [comment]
You need build tools installed
on ubuntu, `apt install build-essential`, on Cent theres probably an equivilent yum meta package
In this case, its looking for g++

**Comment by gehnster** [comment]
That did it, thanks. May want to add that requirement to the Readme?
