### ISSUE TITLE
strict mode error

### ISSUE THREAD

**Issue by z3t0** [screeps/screeps#51]
I just created a new screeps server and on running screeps start I am getting an odd error:

```
Child runtime process 19793 exited with code=1 signal=null
Runtime worker reset due to child exit: code=1 signal=null user=MichaelBot (a1123272b261687) promise pending=true
[backend] process 19802 started
Game time set to 10
New child runtime process 19807
New child runtime process 19808
/usr/local/lib/node_modules/screeps/node_modules/@screeps/backend/lib/index.js:21
        for(let i in config.common.bots) {
            ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/screeps/node_modules/@screeps/backend/bin/start.js:2:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
[backend] process 19802 exited with code 1, restarting...
/usr/local/lib/node_modules/screeps/node_modules/@screeps/driver/lib/runtime.js:117
/usr/local/lib/node_modules/screeps/node_modules/@screeps/driver/lib/runtime.js:117
        let runtimeData = data[0];
        let runtimeData = data[0];
        ^^^
        ^^^


SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
    at node.js:968:3
```

**Comment by gabryatfendor** [comment]
I have the same issue, how did you solved it?

**Comment by z3t0** [comment]
Updating node

**Comment by gabryatfendor** [comment]
Solved with that, thanks.
