### ISSUE TITLE
backend process exited with code 1

### ISSUE THREAD

**Issue by askdaddy** [screeps/screeps#63]
```
Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/screeps/node_modules/weak/build/weakref.node
 → /usr/lib/node_modules/screeps/node_modules/weak/build/Debug/weakref.node
 → /usr/lib/node_modules/screeps/node_modules/weak/build/Release/weakref.node
 → /usr/lib/node_modules/screeps/node_modules/weak/out/Debug/weakref.node
 → /usr/lib/node_modules/screeps/node_modules/weak/Debug/weakref.node
 → /usr/lib/node_modules/screeps/node_modules/weak/out/Release/weakref.node
 → /usr/lib/node_modules/screeps/node_modules/weak/Release/weakref.node
 → /usr/lib/node_modules/screeps/node_modules/weak/build/default/weakref.node
 → /usr/lib/node_modules/screeps/node_modules/weak/compiled/6.11.3/linux/x64/weakref.node
    at bindings (/usr/lib/node_modules/screeps/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/screeps/node_modules/weak/lib/weak.js:7:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at new D (/usr/lib/node_modules/screeps/node_modules/dnode/index.js:28:20)
Loading mods from "/home/seven/mods.json"
Connecting to storage
/usr/lib/node_modules/screeps/node_modules/bindings/bindings.js:96
  throw err
  ^
```

*
Linux ubuntu 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
*

*nodejs v6.11.3*

**Comment by Aeres-Blade** [comment]
Got the same error (trying to run server on a Raspberry Pi 2)
Node : v8.7.0
Npm : v5.4.2

**Comment by Aeres-Blade** [comment]
Managed to fix it : 
- go to node_modules directory and give 777 permissions to all files ("sudo find . -type d -exec chmod 777 {} \;")
- npm rebuild
And now everything works correctly

**Comment by pokemane** [comment]
I'm getting this too but changing the file permissions and rebuilding isn't getting me anywhere.  I've tried making sure the folder has the proper ownership, the files have the right permissions, etc and even tried running as root with/out `sudo` just to see if I could brute force it, but nothing.

I'm on an ubuntu 16.04 LTS container, LXC running in proxmox.  I've had a screeps server running before in this setup, I don't know what happened "recently" that may have changed anything.  It's been a few months since I've tried to update/run it.  I tried both the "original" container running my first screeps server and a brand new blank 16.04 container, both have the same issue.

**Comment by FlyBirdF** [comment]
hi ,i have same problem 
here is the engine_main.log

Error: Could not locate the bindings file. Tried:
 → D:\screeps\node_modules\weak\build\weakref.node
 → D:\screeps\node_modules\weak\build\Debug\weakref.node
 → D:\screeps\node_modules\weak\build\Release\weakref.node
 → D:\screeps\node_modules\weak\out\Debug\weakref.node
 → D:\screeps\node_modules\weak\Debug\weakref.node
 → D:\screeps\node_modules\weak\out\Release\weakref.node
 → D:\screeps\node_modules\weak\Release\weakref.node
 → D:\screeps\node_modules\weak\build\default\weakref.node
 → D:\screeps\node_modules\weak\compiled\8.11.3\win32\x64\weakref.node
    at bindings (D:\screeps\node_modules\bindings\bindings.js:93:9)
    at Object.<anonymous> (D:\screeps\node_modules\weak\lib\weak.js:7:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at new D (D:\screeps\node_modules\dnode\index.js:28:20)
Loading mods from "D:\screeps\mods.json"
Connecting to storage
D:\screeps\node_modules\bindings\bindings.js:96
  throw err

I'm run on windows 7 Ultimate x64 , how can i fixed it .

**Comment by o4kapuk** [comment]
Is it still a thing?
