### ISSUE TITLE
ERR Cannot find module 'nan'

### ISSUE THREAD

**Issue by fipso** [screeps/screeps#7]
Hello,
when running `npm install -g screeps` it fails.
I am running Ubuntu 15.0.4
`nodejs --version` gives me `v0.10.44`
Any ideas about how to fix this ?

```module.js:340
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:575:25)
    at startup (node.js:80:7)
    at node.js:945:3
gyp: Call to 'node -e "require('nan')"' returned exit status 8 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.19.0-65-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-C" "native"
gyp ERR! cwd /usr/lib/node_modules/screeps/node_modules/@screeps/driver/native
gyp ERR! node -v v0.10.44
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 3.19.0-65-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "screeps"
npm ERR! node v0.10.44
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE

npm ERR! @screeps/driver@1.0.0 install: `node-gyp rebuild -C native`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @screeps/driver@1.0.0 install script 'node-gyp rebuild -C native'.
npm ERR! This is most likely a problem with the @screeps/driver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild -C native
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @screeps/driver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls @screeps/driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/screeps/npm-debug.log
```

EDIT:
I did `npm install -g nan`
Now i get when installing screeps:

```In file included from ../src/main.cc:2:0:
../src/pf.h: In member function ‘void screeps::open_closed_t::clear()’:
../src/pf.h:161:9: error: ‘numeric_limits’ is not a member of ‘std’
     if (std::numeric_limits<unsigned int>::max() - 2 <= marker) {
         ^
../src/pf.h:161:29: error: expected primary-expression before ‘unsigned’
     if (std::numeric_limits<unsigned int>::max() - 2 <= marker) {
                             ^
../src/pf.h:161:29: error: expected ‘)’ before ‘unsigned’
../src/pf.h: At global scope:
../src/pf.h:383:61: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
    const cost_t obstacle = std::numeric_limits<cost_t>::max();
                                                             ^
../src/pf.h:383:28: error: ‘numeric_limits’ is not a member of ‘std’
    const cost_t obstacle = std::numeric_limits<cost_t>::max();
                            ^
../src/pf.h:383:54: error: expected primary-expression before ‘>’ token
    const cost_t obstacle = std::numeric_limits<cost_t>::max();
                                                      ^
../src/pf.h:383:55: error: ‘::max’ has not been declared
    const cost_t obstacle = std::numeric_limits<cost_t>::max();
                                                       ^
../src/pf.h:383:55: note: suggested alternative:
In file included from /usr/include/c++/4.9/algorithm:61:0,
                 from ../../../../../../nan/nan.h:50,
                 from ../src/main.cc:1:
/usr/include/c++/4.9/bits/stl_algobase.h:261:5: note:   ‘std::max’
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
native.target.mk:87: recipe for target 'Release/obj.target/native/src/main.o' failed
make: *** [Release/obj.target/native/src/main.o] Error 1
make: Leaving directory '/usr/lib/node_modules/screeps/node_modules/@screeps/driver/native/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.19.0-65-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-C" "native"
gyp ERR! cwd /usr/lib/node_modules/screeps/node_modules/@screeps/driver/native
gyp ERR! node -v v0.10.44
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 3.19.0-65-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "screeps"
npm ERR! node v0.10.44
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
```

**Comment by fipso** [comment]
I thought that Ubuntu 15.10 is using NodeJs 4 or higher by default.
After installing NodeJs 4 everything is working.
