### ISSUE TITLE
Game rooms do not load

### ISSUE THREAD

**Issue by CuAnnan** [screeps/screeps#85]
The client shows the world map.

When I try to choose a room to start in, the screen goes grey and nothing happens.

The output of the backend process reads:

Unhandled rejection: Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\express\lib\response.js:719:10)
    at ServerResponse.send (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\express\lib\response.js:164:12)
    at ServerResponse.json (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\express\lib\response.js:250:15)
    at D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q-json-response\q-json-response.js:17:14
    at _rejected (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:844:24)
    at D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:870:30
    at Promise.when (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:788:41)
Unhandled rejection: Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\express\lib\response.js:719:10)
    at ServerResponse.json (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\express\lib\response.js:247:10)
    at D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q-json-response\q-json-response.js:17:14
    at _rejected (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:844:24)
    at D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:870:30
    at Promise.when (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:788:41)
    at D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:604:44

**Comment by o4kapuk** [comment]
We recently performed a significant performance and stability improvements which should fix issues like this.
If you still experience the issue with the latest server and client, feel free to re-create the issue with a short description of your hardware.

setHeader errors in the log files are irrelevant
