### ISSUE TITLE
Screeps 1.04 gets in process restart loop on Ubuntu 14.04

### ISSUE THREAD

**Issue by mnpenner** [screeps/screeps#9]
I had screeps running fine on Win10 (via Bash on Ubuntu anyway), but I can't get it to run on Ubuntu 14.04.

Trying with node `v7.1.0`. I just get continuous restarts:

```bash
# screeps start
Server build 35
Starting all processes. Ports: 21025 (game), 21026 (cli)
[storage] process 6720 started
[backend] process 6732 started
[engine_main] process 6733 started
[engine_runner1] process 6739 started
[engine_runner2] process 6745 started
[engine_processor1] process 6751 started
[engine_processor2] process 6757 started
[engine_main] process 6733 exited with code 1, restarting...
[engine_runner2] process 6745 exited with code 1, restarting...
[engine_runner1] process 6739 exited with code 1, restarting...
[engine_processor1] process 6751 exited with code 1, restarting...
[engine_processor2] process 6757 exited with code 1, restarting...
[backend] process 6732 exited with code 1, restarting...
[engine_main] process 6772 started
[engine_runner2] process 6778 started
[engine_runner1] process 6779 started
[engine_processor1] process 6785 started
[engine_processor2] process 6791 started
[backend] process 6802 started
```

Inspecting the log files I can see:

```
Error: Cannot find module './core/index'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.getDriver (/usr/lib/node_modules/screeps/node_modules/@screeps/engine/dist/utils.js:21:18)
    at Object.<anonymous> (/usr/lib/node_modules/screeps/node_modules/@screeps/engine/dist/runner.js:8:20)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```

And listing that dir, the file `./core/index` does appear to be missing:

```
# ll /usr/lib/node_modules/screeps/node_modules/@screeps/engine/dist/
total 104
drwxr-xr-x 5 nobody root  4096 Nov 10 00:31 ./
drwxr-xr-x 4 nobody root  4096 Nov 10 00:31 ../
-rw-r--r-- 1 nobody root   301 Nov  7 02:36 config.js
-rw-r--r-- 1 nobody root  3650 Nov  7 02:36 decycle.js
drwxr-xr-x 2 nobody root  4096 Nov 10 00:31 game/
-rw-r--r-- 1 nobody root   179 Nov  8 06:18 index.js
-rw-r--r-- 1 nobody root   103 Nov  7 02:36 local-config.js
-rwxr-xr-x 1 nobody root  4381 Nov  9 04:34 main.js*
drwxr-xr-x 3 nobody root  4096 Nov 10 00:30 processor/
-rwxr-xr-x 1 nobody root 19216 Nov  9 04:34 processor.js*
-rwxr-xr-x 1 nobody root  3503 Nov  9 04:34 runner.js*
drwxr-xr-x 4 nobody root  4096 Nov 10 00:31 sourcemaps/
-rw-r--r-- 1 nobody root 34976 Nov  8 06:09 utils.js
```

Please let me know if you need more info.

**Comment by jirwong** [comment]
Hitting the same problem here with debian 8.6.

**Comment by artch** [comment]
Could you please run this:
```
ls /usr/lib/node_modules/screeps/node_modules/@screeps
```

**Comment by artch** [comment]
Could you please show the entire `engine` log? I guess the real problem is above the `Error: Cannot find module './core/index` line.

**Comment by fipso** [comment]
I have the same Problem in ubuntu 15.10 with node 7.1.0
All log files contain:
```
module.js:474
    throw err;
    ^

Error: Cannot find module './core/index'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.getDriver (/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/@screeps/engine/dist/utils.js:21:18)
    at Object.<anonymous> (/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/@screeps/engine/dist/processor/intents/movement.js:7:20)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
module.js:474
    throw err;
    ^```

**Comment by artch** [comment]
Is there a module `@screeps/driver` installed? Did any errors occur during `npm install`? Do you have Python 2 installed?

**Comment by fipso** [comment]
Yes I have python2.
Installation was working with no problems after fixing a permission Problem.

```root@vps219034:~# npm list -g | grep screeps
├─┬ @screeps/driver@1.0.1 (git://github.com/screeps/driver.git#ff89764e3fa10f3a89edd1bba2ddc7415f2685ee)
└─┬ screeps@1.0.5
  ├─┬ @screeps/backend@1.0.2
  ├── @screeps/common@1.0.1
  ├─┬ @screeps/driver@1.0.1
  ├─┬ @screeps/engine@1.0.2
  ├─┬ @screeps/launcher@1.0.4
  ├─┬ @screeps/pathfinding@0.4.16
  └─┬ @screeps/storage@1.0.2
root@vps219034:~#```

**Comment by artch** [comment]
Please try the updated 1.0.5 package.

**Comment by fipso** [comment]
I did. Still the same error.

```root@vps219034:~/screeps# npm list -g | grep screeps
├─┬ @screeps/driver@1.0.1 (git://github.com/screeps/driver.git#ff89764e3fa10f3a89edd1bba2ddc7415f2685ee)
└─┬ screeps@1.0.5
  ├─┬ @screeps/backend@1.0.2
  ├── @screeps/common@1.0.1
  ├─┬ @screeps/driver@1.0.1
  ├─┬ @screeps/engine@1.0.2
  ├─┬ @screeps/launcher@1.0.4
  ├─┬ @screeps/pathfinding@0.4.16
  └─┬ @screeps/storage@1.0.2
root@vps219034:~/screeps#```

**Comment by fipso** [comment]
The error in the logfiles changed. Now I get

```module.js:474
    throw err;
    ^

Error: Cannot find module '../native/build/Release/native'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/@screeps/driver/lib/index.js:932:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)```

**Comment by artch** [comment]
This error indicates that installation of the `@screeps/driver` module was not successful after all -- the native code has not been compiled. Please see the output of `npm install` for clues of what happened.

**Comment by fipso** [comment]
When running `npm install screeps -g` my bash gets spammed with 

```gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp/4.4.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp"
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp/4.4.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp"
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp/4.4.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp"
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp/4.4.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp"
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp/4.4.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp"
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp/4.4.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp"
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp^C WARN EACCES user "root" does not have permission to access the dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp/4.4.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp"
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp/4.4.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/node_modules/weak/.node-gyp"
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

```
When i abort the installation and run `npm install screeps -g` again. The installation runs without any errors

```root@vps219034:~/screeps# npm install screeps -g
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/root/.nvm/versions/node/v7.1.0/bin/screeps -> /root/.nvm/versions/node/v7.1.0/lib/node_modules/screeps/bin/screeps.js
/root/.nvm/versions/node/v7.1.0/lib
└── screeps@1.0.5
```

**Comment by artch** [comment]
Can't really help you with this, it is some kind of system setup problem on your side that causes the npm compiler to be unable to run. This issue is not related to the Screeps project, but to `npm` and `node-gyp` itself, try to look for some support in the community.

**Comment by jirwong** [comment]
@fipso I did a fresh install, and it's working perfectly for me now. Seems to be related to the node-gyp though, you might want to make sure the npm completes fully before doing anything.

So if it helps, you might want to do the following, that's what I did anyway -

`sudo apt-get update 
sudo apt-get install build-essential
sudo npm uninstall -g screeps
sudo npm install -g screeps`

It took a while for the whole thing to finish, but that's probably just my potato server being so slow.

(Running it on Debian 8.6 Jessie btw)

**Comment by fipso** [comment]
Thx, will try this on a clean installed server soon

**Comment by mnpenner** [comment]
Got mine working too. Might have just needed [some swap](https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04).

**Comment by scaytrase** [comment]
For me purging npm and node_modules worked. Server is running now ok

**Comment by fipso** [comment]
Mine is working now, too. Just installed screeps in local folder (without -g).

**Comment by geekbeard** [comment]
@mnpenner Is right! After many attempts to solve the restart and failed driver installation (had all the above mentioned errors) - what helped was:

`sudo npm uninstall -g screeps`

Follow this: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
to make a swap file. 

Can also use a script made from that tut: https://github.com/Cretezy/Swap

And then install screeps again:

sudo npm install -g screeps

No restarts:)

**Comment by Commandelicious** [comment]
If you are on something like this "Linux bananapi 3.4.39-BPI-M3-Kernel #1 SMP PREEMPT Tue May 3 13:47:01 UTC 2016 armv7l armv7l armv7l GNU/Linux" 
This here might help: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

I tried to updare node a few times and it said all the time it was up to date and I guarantee you 4.x isn't up to date.

**Comment by Patrick-DE** [comment]
For me it worked like that:
```
sudo npm install -g screeps --unsafe-perm
```
