### ISSUE TITLE
Debian 8 - build error on 'npm install screeps'

### ISSUE THREAD

**Issue by Splitframe** [screeps/screeps#97]
Sadly I am unable to switch to Debian 9 or Ubuntu on this machine.
I followed the linked instructions aside from using a debian 8 version of mongodb 
and I tried nodejs v8 and v11.

edit: I already fixed the apt update errors from the missing mirrors and backports for debian 8

The error is the following:

```
isolated_vm.target.mk:125: recipe for target 'Release/obj.target/isolated_vm/src/isolate/holder.o' failed
make: Leaving directory '/home/screeps/world/node_modules/isolated-vm/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.0-0.bpo.4-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
gyp ERR! cwd /home/screeps/world/node_modules/isolated-vm
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/screeps/world/package.json'
npm WARN world No description
npm WARN world No repository field.
npm WARN world No README data
npm WARN world No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isolated-vm@1.7.10 install: `node-gyp rebuild --release -j 4`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isolated-vm@1.7.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/screeps/.npm/_logs/2019-04-05T22_21_16_410Z-debug.log
```

**Comment by o4kapuk** [comment]
That sounds like an isolated-vm issue, are you able to install it alone? If no, please create the issue at [ivm module page](https://github.com/laverdet/isolated-vm).

**Comment by Ratstail91** [comment]
I'm having the same error.

**Comment by Ratstail91** [comment]
I resolved my error - it turns out the version of isolated-vm that I was trying to install and build was incorrect. Instead, I used the version that screeps installed itself. I know this is likely an unrelated cause from this issue though.
